### ISSUE TITLE
VEP slow to annotate

### ISSUE THREAD

**Issue by bmuchmore** [aschluter/ClinPrior#1]
Hi,

First, thank you for your hard work and the open source software.

Second, VEP published their own recommendations (https://useast.ensembl.org/info/docs/tools/vep/script/vep_other.html) to get things to run faster, and the line that catches my eye is the following:

"Consider if you need to generate HGVS notations (--hgvs); this is a complex annotation step that can add ~50-80% to your runtime."

So, my main question if there any chance we can drop the "--hgvs" flag, but still run ClinPrior?

Thanks.

-Brian

**Comment by aschluter** [comment]
Hi Brian,

Thank you for using ClinPrior and asking this question. Unfortunately ClinPrior uses the hgvs protein and hgvc cDNA annotation to predict the variant damage. I didn't know about the runtime limitation due to the hgvs annotation, good to know, but getting the standard nomenclature is an important issue to predict the variant.

Agatha
